- name: configure frontend server
  hosts: frontend
  become: yes
  # vars:
  #   login_host: db.itsgouthamrohan.site
  #   login_password: ExpenseApp@1
  tasks:
  - name: install nginx server
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes     

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes     